### ISSUE TITLE
Meta-issue: Update some of Tueplots' continuous integration and build-process

### ISSUE THREAD

**Issue by pnkraemer** [pnkraemer/tueplots#136]
It has been a while since Tueplots' continuous integration and build process have been updated. 

The following changes would improve the developer's experience:

- [ ] #132 
- [ ] Increase the required Python version to 3.9 <= version <= 3.12. The constraint >= 3.9 matches matplotlib. Update all Github Actions as well. (Choose something in the middle for the docs and linting, e.g., 3.11?). 
- [ ] Increase the version number of all Github Actions to v4 
- [ ] Unify formatting, linting, and continuous integration by bundling up black, isort, pylint, etc., with the pre-commit hook. The likely solution would be to move all formatting and linting to the pre-commit hook and to call `pre-commit run --all-files` in the GitHub Action. It might also be time to move to Ruff instead of pylint+black+isort. Remember to update the developer guidelines.
- [ ] Should we replace tox with a makefile once the linting issue has been resolved? Remember to update the developer guidelines.
